###

GET http://localhost:3000/main HTTP/1.1

###

GET http://localhost:3000/board/qna HTTP/1.1

###

GET http://localhost:3000/article/624c6ba69e2e7f2876744b8a HTTP/1.1

###

POST http://localhost:3000/board/create HTTP/1.1
content-type: application/json

{
    "title": "qna",
    "slug": "qna"
}

###

POST http://localhost:3000/article/create HTTP/1.1
content-type: application/json

{
    "author":"61fa48932b5bc93e0b0f27ee",
    "title": "저자는 유저",
    "content": "2안녕하세요 할수있나요?",
    "board": "623d6912df87930d9bdc68eb"
}

###

POST http://localhost:3000/article/create HTTP/1.1
content-type: application/json

{
    "author":"61f8161eac714bdf22e4fb1c",
    "title": "안녕하세요~",
    "content": "안녕하세요 저는 1년차 웹개발자입니다. 반갑습니다",
    "board": "623d67274014912301a4ffdc"
}

###

patch http://localhost:3000/article/update HTTP/1.1
content-type: application/json

{
    "id": "623d7b69f12da3ad0abc44d2",
    "author":"61f8161eac714bdf22e4fb1c",
    "title": "(수정)",
    "content": "(수정)"
}

###
delete http://localhost:3000/article/delete HTTP/1.1
content-type: application/json

{
    "id": "623d7490e1559d411ad15bae",
    "author":"61f8161eac714bdf22e4fb1c"
}

//댓글
###

POST http://localhost:3000/comment/create HTTP/1.1
content-type: application/json

{
    "author":"6225b98d32838780f5009ca6",
    "article": "624c6ba69e2e7f2876744b8a",
    "content": "테스트3"
}